/*
 * This source file was generated by the Gradle 'init' task
 */
package org.ferranferri.adventofcode2024;

public class App {

    public static void main(String[] args) {
        DayOneProblem dayOneProblem = new DayOneProblem("/day001/ex1/input.txt");
        System.out.println("Day 01 - Part01: " + dayOneProblem.solveProblemDayOnePartOne());
        System.out.println("Day 01 - Part02: " + dayOneProblem.solveProblemDayOnePartTwo());
    }
}
