/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;
import java.util.Objects;

public class App {
    public static void main(String[] args) {
        final String FILE_PATH = "/day001/ex1/input.txt";

        // Load the file from resources using getClass().getResource()
        String filePath = Objects.requireNonNull(App.class.getResource(FILE_PATH)).getPath();

        // Check if the file exists before reading it
        if (filePath != null) {
            try {
                // Read all lines from the file into a List of Strings
                List<String> lines = Files.readAllLines(Paths.get(filePath));

                // Process the lines
                for (String line : lines) {
                    System.out.println(line);
                }

            } catch (IOException | NullPointerException e) {
                e.printStackTrace();
            }
        } else {
            System.out.println("File not found in resources.");
        }

    }
}
