/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;
import java.util.Objects;
import java.util.logging.Logger;
import java.util.stream.IntStream;

import static java.lang.Math.abs;

public class App {
    private static final Logger logger = Logger.getLogger(App.class.getName());
    public static void main(String[] args) {
        System.out.println("Day 01 - Part01: " + solveProblemDayOnePartOne());
    }

    public static int solveProblemDayOnePartOne() {
        final String FILE_PATH = "/day001/ex1/input.txt";

        // Load the file from resources using getClass().getResource()
        String filePath = Objects.requireNonNull(App.class.getResource(FILE_PATH)).getPath();

        // Check if the file exists before reading it
        if (filePath != null) {
            try {
                // Read all lines from the file into a List of Strings
                List<String> lines = Files.readAllLines(Paths.get(filePath));
                List<Integer> firstColumn = lines.stream()
                        .map(line -> line.split(" {3}"))
                        .map(parts -> Integer.parseInt(parts[0]))
                        .sorted()
                        .toList();
                List<Integer> secondColumn = lines.stream()
                        .map(line -> line.split(" {3}"))
                        .map(parts -> Integer.parseInt(parts[1]))
                        .sorted()
                        .toList();

                return IntStream.range(0, firstColumn.size())
                        .map(index -> abs(firstColumn.get(index) - secondColumn.get(index)))
                        .sum();


            } catch (IOException | NullPointerException e) {
                logger.warning("Something went wrong executing program");
            }
        } else {
            System.out.println("File not found in resources.");
        }
        return 0;
    }
}
